name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and package
        run: |
          if [ -f pom.xml ]; then
            echo "Using Maven"
            mvn package
            JAR_FILE=$(mvn help:evaluate -Dexpression=project.build.directory -q -DforceStdout)/$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout).jar
            echo "JAR_file=$JAR_FILE" >> "$GITHUB_ENV"
          elif [ -f build.gradle ]; then
            echo "Using Gradle"
            gradle build
            JAR_FILE=$(gradle -q properties --property buildDir | cut -d ':' -f2- | tr -d '[:space:]') \
                      /libs/$(gradle -q properties --property name | cut -d ':' -f2- | tr -d '[:space:]') \
                      -$(gradle -q properties --property version | cut -d ':' -f2- | tr -d '[:space:]').jar
            echo "JAR_file=$JAR_FILE" >> "$GITHUB_ENV"
          else
            echo "No build tool found"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app.jar
          path: ${{ env.JAR_file }}
